server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/akashmulik/car.ms.config.git
          search-paths:
          - '*-service'
  application:
    name: car.cloud.config
    
logging:
  path: /home/pi/LOGS